apiVersion: v1
kind: Service
metadata:
  name: {{ include "dnscrypt-proxy.fullname" . }}-udp
  labels:
    {{- include "dnscrypt-proxy.labels" . | nindent 4 }}
{{- if .Values.serviceUDP.annotations }}
  annotations:
{{ toYaml .Values.serviceUDP.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.serviceUDP.type }}
  {{- if .Values.serviceUDP.loadBalancerIP }}
  loadBalancerIP: {{ .Values.serviceUDP.loadBalancerIP }}
  {{- end }}
  {{- if or (eq .Values.serviceUDP.type "NodePort") (eq .Values.serviceUDP.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.serviceUDP.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: 53
      targetPort: 5053
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "dnscrypt-proxy.selectorLabels" . | nindent 4 }}
