image:
  repository: klutchell/dnscrypt-proxy
  pullPolicy: IfNotPresent
  tag: 2.0.44

serviceTCP:
  type: NodePort
  externalTrafficPolicy: Local
  loadBalancerIP: ""
  annotations: {}

serviceUDP:
  type: NodePort
  externalTrafficPolicy: Local
  loadBalancerIP: ""
  annotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# -- dnscrypt-proxy TOML configuration ([see docs](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Configuration))
config: ""

# -- used for Helm chart testing only (see [test-dns-proxy.yaml](./charts/dnscrypt-proxy/templates/tests/test-dns-proxy.yaml))
clusterDomain: ""
